[package]
name = "rustos-x86_64"
version = "0.1.0"
authors = ["vanJker"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23"
